# Generated by Django 2.0.3 on 2018-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
